server:
  port: 8088

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

  jpa:
    show-sql: true
